name: Deploy to CloudHub 2.0

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 11
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set Dynamic Version Using GitHub Run Number
        run: |
          version="1.0.${{ github.run_number }}"
          echo "Using dynamic version: $version"
          echo "APP_VERSION=$version" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=$version
          mvn versions:commit

      - name: Configure Maven Settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>anypoint-exchange-v3</id>
                <username>~~~Client~~~</username>
                <password>${{ secrets.CLIENT_ID }}~?~${{ secrets.CLIENT_SECRET }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Package Application
        run: mvn clean package -DmuleDeploy

      - name: Publish to Exchange
        run:  mvn deploy -e -X -DskipTests

      - name: Deploy to CloudHub 2.0 - Branch based
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "Deploying to Sandbox Environment"
            mvn deploy -DmuleDeploy \
              -DskipExchangePreDeploy=false \
              -Danypoint.username=${{ secrets.ANYPOINT_USERNAME }} \
              -Danypoint.password=${{ secrets.ANYPOINT_PASSWORD }} \
              -Ddeploy.environment=Sandbox \
              -Danypointplatform.id=a9878feeb0c143708b452952d9a6b49d \
              -Danypointplatform.secret=5AAC519C7D9e4375aa1cA3f693AFA71d
          elif [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "Deploying to Dev Environment"
            mvn deploy -DmuleDeploy \
              -DskipExchangePreDeploy=false \
              -Danypoint.username=${{ secrets.ANYPOINT_USERNAME }} \
              -Danypoint.password=${{ secrets.ANYPOINT_PASSWORD }} \
              -Ddeploy.environment=Dev \
              -Danypointplatform.id=2672e19c47fb486f9d20711e85f915e4 \
              -Danypointplatform.secret=7979f647C7b14A9DbbeEe97b07c6b08D -e -X
          else
            echo "No deployment environment configured for this branch."
            exit 1
          fi
